version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: meu_stack_app
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure

  api:
    image: meu_stack_api
    depends_on:
      - db
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  db_data: